export interface ExtendedArtist {
  name: string
  genre: 'rock' | 'electronic' | 'hiphop' | 'pop' | 'indie' | 'latin'
  slot: 'headliner' | 'sub-headliner' | 'opener'
  energy: 'low' | 'medium' | 'high'
  era: 'classic' | 'modern' | 'rising'
  vibes: string[]
}

export const EXTENDED_ARTISTS_DB: ExtendedArtist[] = [
  // ─── Rock ──────────────────────────────────────────────────────────────────
  {
    name: "Foo Fighters",
    genre: "rock",
    slot: "headliner",
    energy: "high",
    era: "classic",
    vibes: ["Desert Oasis", "Urban Jungle"],
  },
  {
    name: "Arctic Monkeys",
    genre: "rock",
    slot: "headliner",
    energy: "medium",
    era: "modern",
    vibes: ["Desert Oasis", "Urban Jungle"],
  },
  {
    name: "The Black Keys",
    genre: "rock",
    slot: "sub-headliner",
    energy: "medium",
    era: "modern",
    vibes: ["Desert Oasis", "Beach Paradise"],
  },
  {
    name: "Queens of the Stone Age",
    genre: "rock",
    slot: "headliner",
    energy: "high",
    era: "classic",
    vibes: ["Desert Oasis"],
  },
  {
    name: "Radiohead",
    genre: "rock",
    slot: "headliner",
    energy: "medium",
    era: "classic",
    vibes: ["Forest Wonderland", "Urban Jungle"],
  },
  {
    name: "Royal Blood",
    genre: "rock",
    slot: "sub-headliner",
    energy: "high",
    era: "modern",
    vibes: ["Urban Jungle", "Desert Oasis"],
  },
  {
    name: "Greta Van Fleet",
    genre: "rock",
    slot: "sub-headliner",
    energy: "high",
    era: "rising",
    vibes: ["Desert Oasis", "Forest Wonderland"],
  },
  {
    name: "Turnstile",
    genre: "rock",
    slot: "sub-headliner",
    energy: "high",
    era: "rising",
    vibes: ["Urban Jungle"],
  },
  {
    name: "IDLES",
    genre: "rock",
    slot: "sub-headliner",
    energy: "high",
    era: "modern",
    vibes: ["Urban Jungle"],
  },
  {
    name: "Fontaines D.C.",
    genre: "rock",
    slot: "opener",
    energy: "medium",
    era: "rising",
    vibes: ["Urban Jungle", "Forest Wonderland"],
  },

  // ─── Electronic ────────────────────────────────────────────────────────────
  {
    name: "Skrillex",
    genre: "electronic",
    slot: "headliner",
    energy: "high",
    era: "modern",
    vibes: ["Urban Jungle", "Desert Oasis"],
  },
  {
    name: "Fred Again..",
    genre: "electronic",
    slot: "headliner",
    energy: "high",
    era: "rising",
    vibes: ["Urban Jungle", "Beach Paradise"],
  },
  {
    name: "Disclosure",
    genre: "electronic",
    slot: "sub-headliner",
    energy: "medium",
    era: "modern",
    vibes: ["Beach Paradise", "Urban Jungle"],
  },
  {
    name: "RUFUS DU SOL",
    genre: "electronic",
    slot: "headliner",
    energy: "medium",
    era: "modern",
    vibes: ["Beach Paradise", "Desert Oasis"],
  },
  {
    name: "Bicep",
    genre: "electronic",
    slot: "sub-headliner",
    energy: "high",
    era: "modern",
    vibes: ["Urban Jungle", "Forest Wonderland"],
  },
  {
    name: "Anyma",
    genre: "electronic",
    slot: "sub-headliner",
    energy: "medium",
    era: "rising",
    vibes: ["Urban Jungle", "Desert Oasis"],
  },
  {
    name: "Four Tet",
    genre: "electronic",
    slot: "sub-headliner",
    energy: "low",
    era: "classic",
    vibes: ["Forest Wonderland", "Beach Paradise"],
  },
  {
    name: "Peggy Gou",
    genre: "electronic",
    slot: "sub-headliner",
    energy: "medium",
    era: "rising",
    vibes: ["Beach Paradise", "Urban Jungle"],
  },
  {
    name: "Bonobo",
    genre: "electronic",
    slot: "sub-headliner",
    energy: "low",
    era: "modern",
    vibes: ["Forest Wonderland", "Beach Paradise"],
  },
  {
    name: "Jamie xx",
    genre: "electronic",
    slot: "sub-headliner",
    energy: "medium",
    era: "modern",
    vibes: ["Urban Jungle", "Forest Wonderland"],
  },
  {
    name: "Charlotte de Witte",
    genre: "electronic",
    slot: "sub-headliner",
    energy: "high",
    era: "rising",
    vibes: ["Urban Jungle", "Desert Oasis"],
  },

  // ─── Hip-Hop ───────────────────────────────────────────────────────────────
  {
    name: "Kendrick Lamar",
    genre: "hiphop",
    slot: "headliner",
    energy: "high",
    era: "modern",
    vibes: ["Urban Jungle", "Desert Oasis"],
  },
  {
    name: "Tyler the Creator",
    genre: "hiphop",
    slot: "headliner",
    energy: "high",
    era: "modern",
    vibes: ["Urban Jungle", "Beach Paradise"],
  },
  {
    name: "JID",
    genre: "hiphop",
    slot: "sub-headliner",
    energy: "high",
    era: "rising",
    vibes: ["Urban Jungle"],
  },
  {
    name: "Denzel Curry",
    genre: "hiphop",
    slot: "sub-headliner",
    energy: "high",
    era: "modern",
    vibes: ["Urban Jungle", "Desert Oasis"],
  },
  {
    name: "Joey Bada$$",
    genre: "hiphop",
    slot: "sub-headliner",
    energy: "medium",
    era: "modern",
    vibes: ["Urban Jungle"],
  },
  {
    name: "Doechii",
    genre: "hiphop",
    slot: "opener",
    energy: "high",
    era: "rising",
    vibes: ["Urban Jungle", "Beach Paradise"],
  },
  {
    name: "Little Simz",
    genre: "hiphop",
    slot: "sub-headliner",
    energy: "medium",
    era: "modern",
    vibes: ["Urban Jungle", "Forest Wonderland"],
  },
  {
    name: "Vince Staples",
    genre: "hiphop",
    slot: "sub-headliner",
    energy: "medium",
    era: "modern",
    vibes: ["Urban Jungle", "Beach Paradise"],
  },
  {
    name: "Earthgang",
    genre: "hiphop",
    slot: "opener",
    energy: "high",
    era: "rising",
    vibes: ["Forest Wonderland", "Urban Jungle"],
  },
  {
    name: "Freddie Gibbs",
    genre: "hiphop",
    slot: "sub-headliner",
    energy: "medium",
    era: "modern",
    vibes: ["Urban Jungle", "Desert Oasis"],
  },

  // ─── Pop ───────────────────────────────────────────────────────────────────
  {
    name: "Dua Lipa",
    genre: "pop",
    slot: "headliner",
    energy: "high",
    era: "modern",
    vibes: ["Beach Paradise", "Urban Jungle"],
  },
  {
    name: "The Weeknd",
    genre: "pop",
    slot: "headliner",
    energy: "medium",
    era: "modern",
    vibes: ["Urban Jungle", "Desert Oasis"],
  },
  {
    name: "Sabrina Carpenter",
    genre: "pop",
    slot: "sub-headliner",
    energy: "high",
    era: "rising",
    vibes: ["Beach Paradise", "Urban Jungle"],
  },
  {
    name: "Chappell Roan",
    genre: "pop",
    slot: "sub-headliner",
    energy: "high",
    era: "rising",
    vibes: ["Beach Paradise", "Forest Wonderland"],
  },
  {
    name: "Tate McRae",
    genre: "pop",
    slot: "opener",
    energy: "high",
    era: "rising",
    vibes: ["Beach Paradise", "Urban Jungle"],
  },
  {
    name: "Billie Eilish",
    genre: "pop",
    slot: "headliner",
    energy: "low",
    era: "modern",
    vibes: ["Forest Wonderland", "Urban Jungle"],
  },
  {
    name: "Olivia Rodrigo",
    genre: "pop",
    slot: "headliner",
    energy: "high",
    era: "rising",
    vibes: ["Urban Jungle", "Beach Paradise"],
  },
  {
    name: "Charli XCX",
    genre: "pop",
    slot: "headliner",
    energy: "high",
    era: "modern",
    vibes: ["Urban Jungle", "Beach Paradise"],
  },
  {
    name: "SZA",
    genre: "pop",
    slot: "headliner",
    energy: "medium",
    era: "modern",
    vibes: ["Beach Paradise", "Forest Wonderland"],
  },
  {
    name: "Raye",
    genre: "pop",
    slot: "sub-headliner",
    energy: "medium",
    era: "rising",
    vibes: ["Urban Jungle", "Beach Paradise"],
  },

  // ─── Indie ─────────────────────────────────────────────────────────────────
  {
    name: "Tame Impala",
    genre: "indie",
    slot: "headliner",
    energy: "medium",
    era: "modern",
    vibes: ["Desert Oasis", "Forest Wonderland"],
  },
  {
    name: "Boygenius",
    genre: "indie",
    slot: "sub-headliner",
    energy: "medium",
    era: "rising",
    vibes: ["Forest Wonderland", "Beach Paradise"],
  },
  {
    name: "Clairo",
    genre: "indie",
    slot: "opener",
    energy: "low",
    era: "rising",
    vibes: ["Forest Wonderland", "Beach Paradise"],
  },
  {
    name: "Men I Trust",
    genre: "indie",
    slot: "opener",
    energy: "low",
    era: "rising",
    vibes: ["Forest Wonderland", "Beach Paradise"],
  },
  {
    name: "Alvvays",
    genre: "indie",
    slot: "opener",
    energy: "medium",
    era: "modern",
    vibes: ["Beach Paradise", "Forest Wonderland"],
  },
  {
    name: "Beach House",
    genre: "indie",
    slot: "sub-headliner",
    energy: "low",
    era: "modern",
    vibes: ["Beach Paradise", "Forest Wonderland"],
  },
  {
    name: "Khruangbin",
    genre: "indie",
    slot: "sub-headliner",
    energy: "low",
    era: "modern",
    vibes: ["Desert Oasis", "Beach Paradise"],
  },
  {
    name: "Japanese Breakfast",
    genre: "indie",
    slot: "opener",
    energy: "medium",
    era: "rising",
    vibes: ["Forest Wonderland", "Beach Paradise"],
  },
  {
    name: "Phoebe Bridgers",
    genre: "indie",
    slot: "sub-headliner",
    energy: "low",
    era: "modern",
    vibes: ["Forest Wonderland"],
  },
  {
    name: "Mac DeMarco",
    genre: "indie",
    slot: "sub-headliner",
    energy: "low",
    era: "modern",
    vibes: ["Beach Paradise", "Forest Wonderland"],
  },

  // ─── Latin ─────────────────────────────────────────────────────────────────
  {
    name: "Bad Bunny",
    genre: "latin",
    slot: "headliner",
    energy: "high",
    era: "modern",
    vibes: ["Beach Paradise", "Urban Jungle", "Desert Oasis"],
  },
  {
    name: "Peso Pluma",
    genre: "latin",
    slot: "headliner",
    energy: "high",
    era: "rising",
    vibes: ["Desert Oasis", "Urban Jungle"],
  },
  {
    name: "Rauw Alejandro",
    genre: "latin",
    slot: "sub-headliner",
    energy: "high",
    era: "rising",
    vibes: ["Beach Paradise", "Urban Jungle"],
  },
  {
    name: "Kali Uchis",
    genre: "latin",
    slot: "sub-headliner",
    energy: "medium",
    era: "modern",
    vibes: ["Beach Paradise", "Forest Wonderland"],
  },
  {
    name: "Fuerza Regida",
    genre: "latin",
    slot: "sub-headliner",
    energy: "high",
    era: "rising",
    vibes: ["Desert Oasis", "Urban Jungle"],
  },
  {
    name: "Young Miko",
    genre: "latin",
    slot: "opener",
    energy: "high",
    era: "rising",
    vibes: ["Urban Jungle", "Beach Paradise"],
  },
  {
    name: "Rosalia",
    genre: "latin",
    slot: "headliner",
    energy: "high",
    era: "modern",
    vibes: ["Urban Jungle", "Desert Oasis"],
  },
  {
    name: "Karol G",
    genre: "latin",
    slot: "headliner",
    energy: "high",
    era: "modern",
    vibes: ["Beach Paradise", "Urban Jungle"],
  },
  {
    name: "Feid",
    genre: "latin",
    slot: "sub-headliner",
    energy: "high",
    era: "rising",
    vibes: ["Beach Paradise", "Urban Jungle"],
  },
  {
    name: "Grupo Frontera",
    genre: "latin",
    slot: "sub-headliner",
    energy: "medium",
    era: "rising",
    vibes: ["Desert Oasis", "Beach Paradise"],
  },
]
